# Generated by Django 2.2.5 on 2019-09-24 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='description',
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(choices=[('sdd', 'Standard Double Room'), ('sdr', 'Superior Double Room'), ('frm', 'Family Room'), ('str', 'Standard Single Room'), ('ssr', 'Superior Single Room'), ('vip', 'VIP Room')], max_length=3, unique=True),
        ),
    ]
