# Generated by Django 2.2.5 on 2019-09-24 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel_app', '0002_auto_20190924_1452'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(choices=[('Standard Double Room', 'Standard Double Room'), ('Superior Double Room', 'Superior Double Room'), ('Family Room', 'Family Room'), ('Standard Single Room', 'Standard Single Room'), ('Superior Single Room', 'Superior Single Room'), ('VIP Room', 'VIP Room')], max_length=20, unique=True),
        ),
    ]
