# Generated by Django 2.2.5 on 2019-09-24 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel_app', '0003_auto_20190924_1456'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='number_of_beds',
        ),
        migrations.RemoveField(
            model_name='room',
            name='price',
        ),
        migrations.AddField(
            model_name='category',
            name='number_of_beds',
            field=models.PositiveSmallIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='category',
            name='price',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
