# Generated by Django 2.2.5 on 2019-09-25 02:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel_app', '0004_auto_20190924_1503'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='image',
            field=models.ImageField(default='default.jpg', upload_to='hotel_pics'),
        ),
    ]
